# Metadata for your course

title:          Introduction to Git and Github
tagline:        Get started with Git and Github in practical way
description:    This course will teach you how you can use the tools that are mostly used by world class developers, 
in this course you will learn how you can set up git and how you can create a repository on github and collaborate with others.

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     git-sparkles
  repo:     lab-starter-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type:           createIssue
  title: Welcome
  body: welcome-text.md
               

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new PR
  description: Add your name to the README.md file in your new PR
  event:           pull_request.opened
  actions:
  - type:         gate
    left: '%payload.pull_request.title%'  # get the title from the pull request object inside of the payload
    operator: ===                         # check for strict equality, see more at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Identity
    right: Add name to README
  - type: respond
    with: pr-opened.md
